/*
** EPITECH PROJECT, 2019
** MUL_rpg_2019
** File description:
** item_ressources.c
*/

#include "rpg.h"

const item_prefab_t item_list[] = {
    {"none",         IID_NO_ITEM,      IT_NONE,     WEAPON_NONE,   0,
     { 1, 133, 32, 32}, AT_NONE,  {0}, CONSID_NONE},
    {"no_helm",      IID_NO_HELM,      IT_HELM,     WEAPON_NONE,   0,
     { 1,  34, 32, 32}, AT_HELM,  {HELM_BARE1}, CONSID_NONE},
    {"no_chest",     IID_NO_CHEST,     IT_CHEST,    WEAPON_NONE,   0,
     { 1,  67, 32, 32}, AT_CHEST, {CHEST_BARE}, CONSID_NONE},
    {"no_pants",     IID_NO_PANTS,     IT_PANTS,    WEAPON_NONE,   0,
     { 1, 100, 32, 32}, AT_PANTS, {PANTS_BARE}, CONSID_NONE},
    {"no_ring",      IID_NO_RING,      IT_RING,     WEAPON_NONE,   0,
     { 1,   1, 32, 32}, AT_NONE,  {0}, CONSID_NONE},
    {"armor1_helm",  IID_ARMOR1_HELM,  IT_HELM,     WEAPON_NONE,   1,
     {34,   1, 32, 32}, AT_HELM,  {HELM_ARMOR1_1}, CONSID_NONE},
    {"armor1_chest", IID_ARMOR1_CHEST, IT_CHEST,    WEAPON_NONE,   1,
     {34,  34, 32, 32}, AT_CHEST, {CHEST_ARMOR1}, CONSID_NONE},
    {"armor1_pants", IID_ARMOR1_PANTS, IT_PANTS,    WEAPON_NONE,   1,
     {34,  67, 32, 32}, AT_PANTS, {PANTS_ARMOR1}, CONSID_NONE},
    {"sword",        IID_SWORD,        IT_WEARABLE, WEAPON_SWORD,  1,
     {34, 100, 32, 32}, AT_NONE,  {0}, CONSID_NONE},
    {"pickaxe",      IID_PICKAXE, IT_WEARABLE,   WEAPON_PICKAXE,  1,
     {34, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"potato",  IID_POTATO,  IT_CONSUMABLE, WEAPON_NONE,    16,
     {67,   1, 32, 32}, AT_NONE, {0}, CONSID_POTATO},
    {"apple",   IID_APPLE,   IT_CONSUMABLE, WEAPON_NONE,    16,
     {67,  34, 32, 32}, AT_NONE, {0}, CONSID_APPLE},
    {"rice",    IID_RICE,    IT_CONSUMABLE, WEAPON_NONE,    16,
     {67,  67, 32, 32}, AT_NONE, {0}, CONSID_RICE},
    {"soup",    IID_SOUP,    IT_CONSUMABLE, WEAPON_NONE,    16,
     {67, 100, 32, 32}, AT_NONE, {0}, CONSID_SOUP},
    {"bandage", IID_BANDAGE, IT_CONSUMABLE, WEAPON_NONE,    16,
     {67, 133, 32, 32}, AT_NONE, {0}, CONSID_BANDAGE},

    {"core_frag_ore", IID_CORE_FRAG,       IT_BLOCK, WEAPON_NONE, 64,
     {100,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_ore", IID_COAL,                     IT_BLOCK, WEAPON_NONE, 64,
     {100,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_ore", IID_COPPER,                   IT_BLOCK, WEAPON_NONE, 64,
     {100,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_ore", IID_IRON,                     IT_BLOCK, WEAPON_NONE, 64,
     {100, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_ore", IID_GOLD,                     IT_BLOCK, WEAPON_NONE, 64,
     {100, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_GLOW_STONE,             IT_BLOCK, WEAPON_NONE, 64,
     {100, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_DRY_DIRT,               IT_BLOCK, WEAPON_NONE, 64,
     {133,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_STONE,                  IT_BLOCK, WEAPON_NONE, 64,
     {133,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COBBLE_STAIR,           IT_BLOCK, WEAPON_NONE, 64,
     {133,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_MOSSIE_COBBLE_STAIR,    IT_BLOCK, WEAPON_NONE, 64,
     {133, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_CONCRET_STAIR,          IT_BLOCK, WEAPON_NONE, 64,
     {133, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_STONE_BRIC_STAIR,       IT_BLOCK, WEAPON_NONE, 64,
     {133, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_DIRT,                   IT_BLOCK, WEAPON_NONE, 64,
     {166,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_STONE,                  IT_BLOCK, WEAPON_NONE, 64,
     {166,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COBBLE,                 IT_BLOCK, WEAPON_NONE, 64,
     {166,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_MOSSIE_COBBLE,          IT_BLOCK, WEAPON_NONE, 64,
     {166, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_CONCRET,                IT_BLOCK, WEAPON_NONE, 64,
     {166, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_STONE_BRICK,            IT_BLOCK, WEAPON_NONE, 64,
     {166, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_GRASS,                  IT_BLOCK, WEAPON_NONE, 64,
     {199,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SOD,                    IT_BLOCK, WEAPON_NONE, 64,
     {199,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_HAY,                    IT_BLOCK, WEAPON_NONE, 64,
     {199,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_CONCRET_SLAB,           IT_BLOCK, WEAPON_NONE, 64,
     {199, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_STONE_BRICK_SLAB,       IT_BLOCK, WEAPON_NONE, 64,
     {199, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_DRY_SAND,               IT_BLOCK, WEAPON_NONE, 64,
     {232,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_GRANITE,                IT_BLOCK, WEAPON_NONE, 64,
     {232,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SAND_STONE_STAIR,       IT_BLOCK, WEAPON_NONE, 64,
     {232,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_DARK_SAND_STONE_STAIR,  IT_BLOCK, WEAPON_NONE, 64,
     {232, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SAND_STONE_BRICK_STAIR, IT_BLOCK, WEAPON_NONE, 64,
     {232, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_BRICK_STAIR,            IT_BLOCK, WEAPON_NONE, 64,
     {232, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_SAND,                   IT_BLOCK, WEAPON_NONE, 64,
     {265,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_DESERT_STONE,           IT_BLOCK, WEAPON_NONE, 64,
     {265,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SAND_STONE,             IT_BLOCK, WEAPON_NONE, 64,
     {265,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_DARk_SAND_STONE,        IT_BLOCK, WEAPON_NONE, 64,
     {265, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SAND_STONE_BRICK,       IT_BLOCK, WEAPON_NONE, 64,
     {265, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_BRICK,                  IT_BLOCK, WEAPON_NONE, 64,
     {265, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_ICE,                    IT_BLOCK, WEAPON_NONE, 64,
     {298,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SAND_STONE_SLAB,        IT_BLOCK, WEAPON_NONE, 64,
     {298,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_DARK_SAND_STONE_SLAB,   IT_BLOCK, WEAPON_NONE, 64,
     {298, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_SAND_STONE_BRICK_SLAB,  IT_BLOCK, WEAPON_NONE, 64,
     {298, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_FROZEN_DIRT,            IT_BLOCK, WEAPON_NONE, 64,
     {331,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_CLAY,                   IT_BLOCK, WEAPON_NONE, 64,
     {331,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_GRAVEL,                 IT_BLOCK, WEAPON_NONE, 64,
     {331,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_IRON_BAR,               IT_BLOCK, WEAPON_NONE, 64,
     {331, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COPPER_BLOCK_STAIR,     IT_BLOCK, WEAPON_NONE, 64,
     {331, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COPPER_FENCE,           IT_BLOCK, WEAPON_NONE, 64,
     {331, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_SNOW,                   IT_BLOCK, WEAPON_NONE, 64,
     {364,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_MUD,                    IT_BLOCK, WEAPON_NONE, 64,
     {364,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_OBSIDIAN,               IT_BLOCK, WEAPON_NONE, 64,
     {364,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_GLASS,                  IT_BLOCK, WEAPON_NONE, 64,
     {364, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COPPER_BLOCK,           IT_BLOCK, WEAPON_NONE, 64,
     {364, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COPPER_WINDOW,          IT_BLOCK, WEAPON_NONE, 64,
     {364, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_LOG,                    IT_BLOCK, WEAPON_NONE, 64,
     {397,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_WOOD,                   IT_BLOCK, WEAPON_NONE, 64,
     {397,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_WINDOW_LATTICE,         IT_BLOCK, WEAPON_NONE, 64,
     {397,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_WOODEN_STAIR,           IT_BLOCK, WEAPON_NONE, 64,
     {397, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COPPER_STAIR,           IT_BLOCK, WEAPON_NONE, 64,
     {397, 133, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_COPPER_SLAB,            IT_BLOCK, WEAPON_NONE, 64,
     {397, 166, 32, 32}, AT_NONE, {0}, CONSID_NONE},

    {"_block", IID_ORNATE_LOG,             IT_BLOCK, WEAPON_NONE, 64,
     {430,   1, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_WOODEN_FENCE,           IT_BLOCK, WEAPON_NONE, 64,
     {430,  34, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_WOODEN_WINDOW,          IT_BLOCK, WEAPON_NONE, 64,
     {430,  67, 32, 32}, AT_NONE, {0}, CONSID_NONE},
    {"_block", IID_WOODEN_SLAB,            IT_BLOCK, WEAPON_NONE, 64,
     {430, 100, 32, 32}, AT_NONE, {0}, CONSID_NONE}
};

const consumable_prefab_t consumable[] = {
    {CONSID_POTATO,  CONST_FOOD,     IID_POTATO,  12,   0, 18},
    {CONSID_APPLE,   CONST_FOOD,     IID_APPLE,    5,   0, 10},
    {CONSID_RICE,    CONST_FOOD,     IID_RICE,    18,   0, 30},
    {CONSID_SOUP,    CONST_FOOD,     IID_SOUP,    26,   0, 50},
    {CONSID_BANDAGE, CONST_MEDICINE, IID_BANDAGE,  8, 100,  0},
    {CONSID_NONE,    CONST_NONE,     IID_NO_ITEM,  0,   0,  0}
};